using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace DevTools.Reward
{
	public static class RewardKeysGenerator
	{
		static readonly Regex IdentifierRegex = new Regex(@"^[A-Za-z_][A-Za-z0-9_]*$");

		public static List<string> Validate(RewardCatalog catalog)
		{
			var errors = new List<string>();

			if (catalog == null)
			{
				errors.Add("Chưa có catalog.");
				return errors;
			}

			if (catalog.rewards.Count == 0)
			{
				errors.Add("Catalog rỗng — thêm ít nhất 1 reward trước khi generate.");
				return errors;
			}

			var seen = new HashSet<string>();

			for (int i = 0; i < catalog.rewards.Count; i++)
			{
				RewardEntry entry = catalog.rewards[i];
				string id = entry?.id ?? "";
				string label = $"Dòng {i + 1}";

				if (string.IsNullOrWhiteSpace(id)) errors.Add($"{label}: chưa đặt id.");
				else if (!IdentifierRegex.IsMatch(id)) errors.Add($"{label}: id '{id}' không phải C# identifier hợp lệ.");
				else if (!seen.Add(id)) errors.Add($"{label}: id '{id}' bị trùng.");
			}

			return errors;
		}

		public static bool Generate(RewardCatalog catalog, string path)
		{
			List<string> errors = Validate(catalog);

			if (errors.Count > 0)
			{
				Debug.LogError("[Reward] Không generate được:\n- " + string.Join("\n- ", errors));
				return false;
			}

			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("// Sinh tu RewardCatalog. Khong sua tay.");
			sb.AppendLine("// Sua bang trong Tools/DevTool -> Rewards roi bam Generate Keys.");
			sb.AppendLine("// </auto-generated>");
			sb.AppendLine();
			sb.AppendLine("public static class RewardKeys");
			sb.AppendLine("{");

			foreach (RewardEntry entry in catalog.rewards)
			{
				sb.AppendLine($"    public const string {entry.id} = \"{entry.id}\";");
			}

			sb.AppendLine("}");

			string full = Path.Combine(Directory.GetCurrentDirectory(), path);
			Directory.CreateDirectory(Path.GetDirectoryName(full));
			File.WriteAllText(full, sb.ToString(), new UTF8Encoding(false));

			AssetDatabase.ImportAsset(path);
			AssetDatabase.Refresh();

			Debug.Log($"<color=cyan>[Reward]</color> Đã generate {path} với {catalog.rewards.Count} key.");
			return true;
		}
	}
}
