// <auto-generated>
// Sinh tu RewardCatalog. Khong sua tay.
// Sua bang trong Tools/DevTool -> Rewards roi bam Generate Keys.
// </auto-generated>

public static class RewardKeys
{
    public const string Coin = "Coin";
    public const string Heart = "Heart";
    public const string HeartUnlimited = "HeartUnlimited";
    public const string Booster0 = "Booster0";
    public const string RemoveAds = "RemoveAds";
}
