// <auto-generated>
// Sinh tu RewardCatalog. Khong sua tay.
// Sua bang trong Tools/DevTool -> Rewards roi bam Generate Keys.
// </auto-generated>

public static class RewardKeys
{
    public const string Coin = "Coin";
    public const string Heart = "Heart";
    public const string HeartUnlimited = "HeartUnlimited";
}
