public enum EventID
{

    NONE,
    //HOME SCRENE
    CHANGE_COIN = 50,
    CHANGE_HEART = 51,
    CHANGE_AVATAR = 52,
    POPUP_OPENED = 53,
    POPUP_CLOSED = 54,
    BOOSTER_USED = 100,

    BLOCK_DESTROYED = 200,
    LEVEL_COMPLETE = 201,
    SHOOTER_FIRED = 202,
    LOOP_MODE_ENTERED = 203,
    CONVEYOR_NOT_ENOUGH_SLOT = 204,

}
